sources:
  - glyphs/OnestBlack.glyphs
  # - glyphs/OnestBold.glyphs
  # - glyphs/OnestExtraBold.glyphs
  # - glyphs/OnestLight.glyphs
  # - glyphs/OnestMedium.glyphs
  # - glyphs/OnestRegular.glyphs
  # - glyphs/OnestThin.glyphs
axisOrder:
  - wght
  - ital
familyName: Onest
